sonar.projectKey=Miguel-gfdez_anonymization-lib
sonar.organization=miguel-gfdez

sonar.sources=src
sonar.tests=tests

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
