name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install package and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install coverage build

      - name: Run unittest with coverage
        run: |
          coverage run --source=src/anonymization_lib \
            -m unittest discover -s tests -p "test_*.py"

          coverage xml

      - name: SonarCloud Scan
        if: github.actor != 'dependabot[bot]'
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build wheel and source distribution
        run: |
          python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-dist
          path: dist/
